Ft enrollment for user
fabmukunzi/posinnove-be pull request #19
Opened 2024-10-28 19:48 UTC by RobertOdhiz

2024-11-11 22:29 UTC, fabmukunzi requested changes

2024-11-11 22:29 UTC, fabmukunzi commented on src/services/enrolloments.services.js
> +        attributes: ['id', 'title']
Let's include all projects data

2024-11-11 22:29 UTC, fabmukunzi commented on src/services/enrolloments.services.js
> +          attributes: ['id', 'firstName', 'lastName', 'email']
add more info like profileImage

2024-11-13 19:04 UTC, RobertOdhiz commented on src/services/enrolloments.services.js
> +        attributes: ['id', 'title']
Have a look at this in the new branch [rf-enrollment here](https://github.com/fabmukunzi/posinnove-be/pull/29)

2024-11-13 19:06 UTC, RobertOdhiz commented on src/services/enrolloments.services.js
> +        attributes: ['id', 'title']
Once [this branch](https://github.com/fabmukunzi/posinnove-be/pull/29) is merged with dev. Then I can resolve the conflicts and then ensure proper data is returned as from the requested changes.

2024-12-19 16:22 UTC, closed without merging