ft/deleting-user-sendingEmails
fabmukunzi/posinnove-be pull request #32
Opened 2024-11-28 13:25 UTC by kayigireerneste

I added sending emails to all users when there is new project created
I added function for deleting user his/her self and sending email to him/her
I added function for deleting user by admin and sending email

2024-11-28 13:43 UTC, fabmukunzi requested changes
Consider having one route for delete user and then check if a user role is an admin or if the userId in param is the same as the userId in the sent token

2024-11-28 13:43 UTC, fabmukunzi commented on src/controllers/project.controller.js
> +            </html>
Create folder for email templates and add this template so that we can import it in this file

2024-11-28 13:43 UTC, fabmukunzi commented on src/controllers/project.controller.js
> +        message: 'Project created successfully, notification emails sent to learners',
Leave this message only `Project created successfully`

2024-11-28 13:43 UTC, fabmukunzi commented on src/controllers/user.controller.js
> +    }
This is already checked in the middleware to check if a user exists by Id. remove this

2024-11-28 13:43 UTC, fabmukunzi commented on src/controllers/user.controller.js
> +          </body>
Consider moving this to the email-templates folder too.

2024-11-28 13:43 UTC, fabmukunzi commented on src/controllers/user.controller.js
> +    }
Let's use a middleware to check if a user exists

2024-11-28 13:43 UTC, fabmukunzi commented on src/controllers/user.controller.js
> +        </html>
Move this to email-templates as well

2024-11-28 13:43 UTC, fabmukunzi commented on src/routes/user.routes.js
> +userRoutes.delete('/userDeleteAccount', protectRoute, deleteOwnAccount);
route should be `/api/users/{userId}` and method delete

2024-12-19 16:20 UTC, amiparadis250 approved these changes

2024-12-19 16:20 UTC, amiparadis250 approved these changes

2024-12-19 16:20 UTC, amiparadis250 approved these changes

2024-12-19 16:20 UTC, amiparadis250 approved these changes

2024-12-19 16:21 UTC, merged