Feature: Feedback and Reviews design
fabmukunzi/posinnove-be pull request #7
Opened 2024-10-04 11:46 UTC by shallomkanyori

Implemented the database designs for mentor feedback and learner reviews.

2024-10-05 07:39 UTC, fabmukunzi requested changes

2024-10-05 07:39 UTC, fabmukunzi commented on src/database/migrations/20241002135601-create-feedback.js
> +        references: {
Why did you prefer using enrollmentId instead of projectId. I think we can use projectId since it contains mentorId as welll

2024-10-05 07:39 UTC, fabmukunzi commented on src/database/migrations/20241003152153-create-reviews.js
> +        type: Sequelize.ENUM("completed", "partially_completed", "dropped"),
Why do we have these statuses? I think they need to be revised

2024-10-05 07:39 UTC, fabmukunzi commented on src/database/migrations/20241003152153-create-reviews.js
> +      },
Why do we need this since we have projectId

2024-10-05 09:18 UTC, shallomkanyori commented on src/database/migrations/20241002135601-create-feedback.js
> +        references: {
The feedback is from a mentor to a learner on the learner's specific implementation of their project. The enrollment is what sets up the relationship between a learner and a project. If we remove the enrollmentId, we'd need to add the userId/learnerId in addition to the projectId.

2024-10-05 09:18 UTC, shallomkanyori commented on src/database/migrations/20241003152153-create-reviews.js
> +        type: Sequelize.ENUM("completed", "partially_completed", "dropped"),
The idea was that a learner can provide a review on a project they've enrolled in and this status shows whether they've completed the project. This status is actually the enrollment status so it can be removed from the review table and maybe add some status options to the enrollment itself.

2024-10-05 09:25 UTC, shallomkanyori commented on src/database/migrations/20241003152153-create-reviews.js
> +      },
A learner gives a review to a project they've enrolled in. The projectId can actually be removed. We can also optionally add a userId/learnerId. These are only to simplify queries: project.getReviews() or user.getReviews(). With only the enrollmentId, such queries can still be implemented with a little effort.

2024-10-07 08:36 UTC, fabmukunzi commented on src/database/migrations/20241002135601-create-feedback.js
> +        references: {
Awesome this makes sense 👏🏾

2024-10-07 08:46 UTC, fabmukunzi commented on src/database/migrations/20241003152153-create-reviews.js
> +        type: Sequelize.ENUM("completed", "partially_completed", "dropped"),
Having status is good Just naming

2024-10-14 18:30 UTC, amiparadis250 approved these changes

2024-10-14 18:31 UTC, merged